M48
; DRILL file {KiCad 8.0.0} date 2024-03-02T01:19:26-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-02T01:19:26-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X3.6539Y-5.15
X3.6539Y-5.25
X3.6539Y-5.35
T2
X3.75Y-3.725
X3.75Y-5.6541
X6.2Y-3.725
X6.2Y-5.6541
M30
